# Generated by Django 3.0.1 on 2019-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteJuridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
